"""Imagens no Vercel Blob

Revision ID: 0aed6c58175a
Revises: 81e99377a701
Create Date: 2026-10-09 15:35:09.127621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aed6c58175a'
down_revision = '81e99377a701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_url', sa.String(length=600), nullable=True))
        batch_op.alter_column('data',
               existing_type=sa.LargeBinary(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.LargeBinary(),
               nullable=False)
        batch_op.drop_column('storage_url')

    # ### end Alembic commands ###
