"""Esquema inicial multiusuario

Revision ID: 31761b9fce13
Revises: 
Create Date: 2026-10-09 14:28:09.992649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31761b9fce13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('recovery_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('can_send_messages', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('MESTRE','ADMIN')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system', sa.String(length=80), nullable=True),
    sa.Column('setting', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('cover_image', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('planejada', 'ativa', 'pausada', 'encerrada')", name='ck_campaign_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('file_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_assets_owner_id'), ['owner_id'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('real_name', sa.String(length=120), nullable=True),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('messaging_consent', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ativo', 'inativo', 'arquivado')", name='ck_player_status'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_status'), ['status'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('campaign_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('ativo','saiu')", name='ck_campaign_player_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'player_id', name='uq_campaign_player')
    )
    with op.batch_alter_table('campaign_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_players_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_players_player_id'), ['player_id'], unique=False)

    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=80), nullable=True),
    sa.Column('race', sa.String(length=80), nullable=True),
    sa.Column('char_class', sa.String(length=80), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('portrait', sa.String(length=100), nullable=True),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('master_notes', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('xp_percent', sa.Integer(), nullable=False),
    sa.Column('xp_cycle', sa.Integer(), nullable=False),
    sa.Column('xp_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ativo', 'afastado', 'aposentado', 'morto')", name='ck_character_status'),
    sa.CheckConstraint('xp_percent BETWEEN 0 AND 100', name='ck_character_xp_percent'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('ix_characters_campaign_name', ['campaign_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_status'), ['status'], unique=False)

    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('pending', sa.Text(), nullable=True),
    sa.Column('master_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('agendada', 'realizada', 'cancelada')", name='ck_session_status'),
    sa.CheckConstraint('number > 0', name='ck_session_number'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'number', name='uq_session_campaign_number')
    )
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_sessions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_sessions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_sessions_title'), ['title'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('moeda', 'tesouro', 'equipamento', 'item_especial', 'consumivel', 'outro')", name='ck_item_category'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)

    op.create_table('message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('chars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("channel IN ('sms','whatsapp')", name='ck_message_channel'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_logs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_logs_player_id'), ['player_id'], unique=False)

    op.create_table('npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('secrets', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('master_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ativo', 'morto', 'desaparecido', 'desconhecido')", name='ck_npc_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('npcs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_npcs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_npcs_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_npcs_status'), ['status'], unique=False)

    op.create_table('character_npc_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.CheckConstraint("kind IN ('alianca', 'rivalidade', 'amizade', 'familiar', 'mentor', 'divida', 'neutro', 'outro')", name='ck_relationship_kind'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'npc_id', 'kind', name='uq_character_npc_kind')
    )
    with op.batch_alter_table('character_npc_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_npc_relationships_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_npc_relationships_npc_id'), ['npc_id'], unique=False)

    op.create_table('experience_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('previous_percent', sa.Integer(), nullable=False),
    sa.Column('new_percent', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('requested_delta', sa.Integer(), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("origin IN ('individual', 'coletiva', 'novo_ciclo')", name='ck_xp_history_origin'),
    sa.CheckConstraint('previous_percent BETWEEN 0 AND 100 AND new_percent BETWEEN 0 AND 100', name='ck_xp_history_range'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experience_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_history_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_history_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_history_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experience_history_created_at'), ['created_at'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('important', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('jogador', 'personagem', 'segredo', 'gancho', 'npc', 'consequencia', 'ideia', 'outros')", name='ck_note_category'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_title'), ['title'], unique=False)

    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('master_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('planejada', 'disponivel', 'em_andamento', 'concluida', 'fracassada', 'abandonada')", name='ck_quest_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quests_npc_id'), ['npc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quests_title'), ['title'], unique=False)

    op.create_table('session_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_events_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_events_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_events_session_id'), ['session_id'], unique=False)

    op.create_table('session_npcs',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'npc_id')
    )
    op.create_table('session_participants',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'character_id')
    )
    op.create_table('character_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=200), nullable=True),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_character_item_quantity'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_items_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_items_item_id'), ['item_id'], unique=False)

    op.create_table('quest_characters',
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quest_id', 'character_id')
    )
    op.create_table('quest_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quest_objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_objectives_quest_id'), ['quest_id'], unique=False)

    op.create_table('quest_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quest_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_status_history_quest_id'), ['quest_id'], unique=False)

    op.create_table('session_quests',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'quest_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_quests')
    with op.batch_alter_table('quest_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_status_history_quest_id'))

    op.drop_table('quest_status_history')
    with op.batch_alter_table('quest_objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_objectives_quest_id'))

    op.drop_table('quest_objectives')
    op.drop_table('quest_characters')
    with op.batch_alter_table('character_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_items_item_id'))
        batch_op.drop_index(batch_op.f('ix_character_items_character_id'))

    op.drop_table('character_items')
    op.drop_table('session_participants')
    op.drop_table('session_npcs')
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_session_events_character_id'))
        batch_op.drop_index(batch_op.f('ix_session_events_campaign_id'))

    op.drop_table('session_events')
    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_title'))
        batch_op.drop_index(batch_op.f('ix_quests_status'))
        batch_op.drop_index(batch_op.f('ix_quests_npc_id'))
        batch_op.drop_index(batch_op.f('ix_quests_campaign_id'))

    op.drop_table('quests')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_title'))
        batch_op.drop_index(batch_op.f('ix_notes_player_id'))
        batch_op.drop_index(batch_op.f('ix_notes_character_id'))
        batch_op.drop_index(batch_op.f('ix_notes_category'))
        batch_op.drop_index(batch_op.f('ix_notes_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_notes_archived'))

    op.drop_table('notes')
    with op.batch_alter_table('experience_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experience_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_experience_history_character_id'))
        batch_op.drop_index(batch_op.f('ix_experience_history_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_experience_history_batch_id'))

    op.drop_table('experience_history')
    with op.batch_alter_table('character_npc_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_npc_relationships_npc_id'))
        batch_op.drop_index(batch_op.f('ix_character_npc_relationships_character_id'))

    op.drop_table('character_npc_relationships')
    with op.batch_alter_table('npcs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_npcs_status'))
        batch_op.drop_index(batch_op.f('ix_npcs_name'))
        batch_op.drop_index(batch_op.f('ix_npcs_campaign_id'))

    op.drop_table('npcs')
    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_logs_player_id'))
        batch_op.drop_index(batch_op.f('ix_message_logs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_message_logs_created_at'))

    op.drop_table('message_logs')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_category'))
        batch_op.drop_index(batch_op.f('ix_items_campaign_id'))

    op.drop_table('items')
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_sessions_title'))
        batch_op.drop_index(batch_op.f('ix_game_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_game_sessions_date'))
        batch_op.drop_index(batch_op.f('ix_game_sessions_campaign_id'))

    op.drop_table('game_sessions')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_status'))
        batch_op.drop_index(batch_op.f('ix_characters_player_id'))
        batch_op.drop_index(batch_op.f('ix_characters_name'))
        batch_op.drop_index('ix_characters_campaign_name')
        batch_op.drop_index(batch_op.f('ix_characters_campaign_id'))

    op.drop_table('characters')
    with op.batch_alter_table('campaign_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_players_player_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_players_campaign_id'))

    op.drop_table('campaign_players')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_status'))
        batch_op.drop_index(batch_op.f('ix_players_owner_id'))
        batch_op.drop_index(batch_op.f('ix_players_display_name'))

    op.drop_table('players')
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_assets_owner_id'))

    op.drop_table('file_assets')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_owner_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_name'))

    op.drop_table('campaigns')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
