"""Liberacao de imagens por usuario

Revision ID: 81e99377a701
Revises: 31761b9fce13
Create Date: 2026-10-09 15:18:06.610470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e99377a701'
down_revision = '31761b9fce13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('images_requested_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('images_requested_at')
        batch_op.drop_column('images_enabled')

    # ### end Alembic commands ###
